### ISSUE TITLE
Validation: python_import attrs check does not work

### ISSUE THREAD

**Issue by Mankro** [apluslms/python-grader-utils#16]
test_config.yaml validation: `python_import` `attrs` does not seem to do anything. At least it failed to see the missing function in the submission module.

The README says that `attrs` should work. 
https://github.com/Aalto-LeTech/python-grader-utils/blob/master/graderutils/README.md

Example `test_config.yaml`:

```
test_groups:
  - module: grader_tests
    display_name: Grader tests

validation:
  display_name: Input validation
  tasks:
    - type: python_import
      display_name: "The submitted file is a Python module that can be imported and defines the function greeting."
      file: submission.py
      attrs:
        greeting: function
    - type: python_syntax
      display_name: "The submitted file has correct Python syntax."
      file: submission.py
```
